### ISSUE TITLE
Fancy hover

### ISSUE THREAD

**Issue by oskarrough** [oskarrough/guss-werk-configurator#8]
To make it easier to connect the menu with the parts of the image that is actually changing, I thought we could explore some hover effect.

- you hover one of the features in the menu
- the corresponding feature on the image is highlighted

since it's transparent pngs, there is a trick!

```css
img { filter: drop-shadow(0px 0px 10px pink); }
```

tricky part is maybe how to hover the right element?
